import { Router } from "express";
import { CategoryController } from "../controllers/category.controller.js";
import { Role } from "../enums/Role.js";
import { authMiddleware } from "../middlewares/authMiddleware.js";
import { authorize } from "../middlewares/authorize.js";
import { validateData } from "../middlewares/validateData.js";
import { CategoryRepository } from "../repositories/CategoryRepository.js";
import { categoryParamsSchema, categoryQueryPaginationSchema, createCategorySchema, updateCategorySchema } from "../schemas/category.schema.js";
import { CategoryService } from "../services/CategoryService.js";
const router = Router();
const categoryRepository = new CategoryRepository();
const categoryService = new CategoryService(categoryRepository);
const categoryController = new CategoryController(categoryService);
router.get("/", validateData(categoryQueryPaginationSchema, "query"), categoryController.getAll);
router.get("/:id", validateData(categoryParamsSchema, "params"), categoryController.getById);
router.post("/", authMiddleware, authorize(Role.ADMIN), validateData(createCategorySchema), categoryController.create);
router.put("/:id", authMiddleware, authorize(Role.ADMIN), validateData(categoryParamsSchema, "params"), validateData(updateCategorySchema), categoryController.update);
router.delete("/:id", authMiddleware, authorize(Role.ADMIN), validateData(categoryParamsSchema, "params"), categoryController.delete);
export default router;
