import { Router } from "express";
import { ProductController } from "../controllers/product.controller.js";
import { Role } from "../enums/Role.js";
import { authMiddleware } from "../middlewares/authMiddleware.js";
import { authorize } from "../middlewares/authorize.js";
import { CategoryRepository } from "../repositories/CategoryRepository.js";
import { ProductRepository } from "../repositories/ProductRepository.js";
import { ProductService } from "../services/ProductService.js";
const router = Router();
const productRepository = new ProductRepository();
const categoryRepository = new CategoryRepository();
const productService = new ProductService(productRepository, categoryRepository);
const productController = new ProductController(productService);
router.get("/", productController.getAll);
router.get("/:id", productController.getById);
router.post("/", authMiddleware, authorize(Role.ADMIN), productController.create);
router.put("/:id", authMiddleware, authorize(Role.ADMIN), productController.update);
router.delete("/:id", authMiddleware, authorize(Role.ADMIN), productController.delete);
export default router;
